name: build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  REDIRECTOR_DEPLOY: false
  FIREBASE_DEPLOY: true
  FIREBASE_PROJECT: tbtx-form
  FIREBASE_SITE: tbtx-form-staging
  GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GCP_SA_KEY }}

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    container:
      image: zerosuxx/client-publish:latest
    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Setup Node
#        uses: actions/setup-node@v3
#        with:
#          node-version-file: '.nvmrc'
#          cache: 'npm'
#
#      - name: Install dependencies
#        run: npm install
#
#      - name: Check lint
#        run: npm run lint
#
#      - name: Run tests
#        run: npm run test
#
#      - name: Build application
#        run: npm run build

      - name: Deploy with client publish
        run: deploy --target-env staging
#        uses: docker://zerosuxx/client-publish
#        with:
#          entrypoint: client-publish
#          args: deploy --target-env staging

#      - name: Deploy to Firebase
#        uses: w9jds/firebase-action@master
#        with:
#          args: deploy --only hosting:tbtx-form-staging
#        env:
#          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
